apiVersion: v1
kind: Service
metadata:
  name: {{ include "ui-app-helm.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - nodePort: {{ .Values.service.nodeport }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetport }}
  selector:
    {{- include "ui-app-helm.selectorLabels" . | nindent 4 }}
